title: OMG WOW
repository: bschofield-va/site-test
description: A test site, cool.

theme: just-the-docs

markdown: GFM
plugins:
  - jemoji
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter

