title: OMG WOW
repository: bschofield-va/site-test
description: A test site, cool.

remote_theme: pages-themes/primer@v0.6.0
markdown: GFM
plugins:
  - jemoji
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter

