title: OMG WOW
repository: bschofield-va/site-test
description: A test site, cool.

theme: jekyll-theme-minimal

markdown: GFM
plugins:
  - jemoji
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter

exclude:
  - Dockerfile
  - compose.yaml


