title: OMG WOW
repository: bschofield-va/site-test
description: A test site, cool.

url: https://bschofield-va.github.io/site-test

theme: jekyll-theme-primer



markdown: GFM
plugins:
  - jemoji
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - compose.yaml

